BE/src/video-server/implementations/openvidu.service.ts
BE/src/video-server/types/openvidu.type.ts

[Refactor] Openvidu service 계층 리팩토링

---

FE/src/components/game/ChattingList.tsx
FE/src/components/lobby/CreateRoomModal.tsx
FE/src/components/lobby/LobbyBanner.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/components/lobby/LobbyList.tsx
FE/src/components/lobby/LobbyViewer.tsx
FE/src/constants/roomStatus.ts
FE/src/stores/socketStore.ts
FE/src/types/chat.ts
FE/src/types/room.ts

https://github.com/user-attachments/assets/153bb6ca-8737-4425-b03d-9375e23f4610
#60 
#64

[Feat] 방 목록 조회 & 게임방 입장 기능 

---

.github/workflows/deploy.yml

#77 
현진님께서 앞서 시크릿 변수를 잘 설정해주셔서 이를 이용하였습니다.
우선 cicd에 필요한 기본적인 build와 의존성 설치는 진행하게 두었으며,
추가로 하단 항목을 검사하도록 설정해두었습니다.
- tsc
- lint
- test coverage 
tsc와 lint는 에러 수준에서만 block될 것으로 예상됩니다.
test coverage 우선 주석처리 해두었습니다.

[Feat] Back-end CI/CD 구축

---

.github/workflows/deploy_FE.yml
FE/src/app/game/[roomId]/page.tsx
FE/src/components/game/Bottombar.tsx
FE/src/components/game/ChattingItem.tsx
FE/src/components/game/ChattingList.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/components/lobby/CreateRoomModal.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/components/lobby/LobbyList.tsx
FE/src/components/lobby/LobbyViewer.tsx
FE/src/components/lobby/NicknameModal.tsx
FE/src/hooks/useOpenVidu.ts
FE/src/stores/socketStore.ts

[Feat] 게임 대기 시 참가자 목록 표시 & 채팅 UI 수정 & 닉네임 설정 기능

---

BE/src/video-server/implementations/openvidu.service.ts

게임 참가자가 게임방에서 나갈 때 openvidu 세션과 연결을 종료시키는 기능이 필요할 거 같아 추가해두었습니다.
가능하다면 frontend 측에서도 나가기 버튼을 누르거나, 뒤로가기를 이행했을 때  세션을 종료하는 코드를 추가해야할 것 같습니다.
#114

[Feat] openvidu 세션 연결 종료 메소드 구현

---

.github/workflows/deploy_FE.yml

[Fix] 프론트엔드 CI/CD 오류 수정

---

.github/workflows/deploy_FE.yml

[Fix] 프론트엔드 CI/CD 수정

---

FE/package-lock.json
FE/package.json
FE/src/components/game/Bottombar.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/constants/role.ts
FE/src/constants/situation.ts

[Feat] 직업 확인 기능

---

FE/src/components/game/ChattingList.tsx
FE/tests/openvidu.test.ts

아래와 같이 수정 전에는 채팅 메세지를 보냈을 때 메세지의 끝 글자가 추가로 전송되는 오류가 존재하였습니다.
이는 한글이 자음과 모음으로 이루어져 있기 때문에 글자를 입력할 때 글자가 조합 중인지, 아니면 조합이 끝난 상태인지 알 수 없기 때문에 발생한 문제입니다. 
해당 문제를 해결하기 위해 입력 문자가 조합 중인지 아닌지를 나타내는 isComposing 프로퍼티를 사용하여 해당 오류를 수정하였습니다.
#136

[Fix] 채팅 메세지 전송 오류 수정

---

FE/src/components/common/Header.tsx
FE/src/components/game/Bottombar.tsx
FE/src/components/game/ChattingItem.tsx
FE/src/components/game/ChattingList.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/components/lobby/LobbyBanner.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/constants/situation.ts
FE/src/hooks/useOpenVidu.ts
FE/src/stores/sidebarStore.ts
FE/src/types/gamePublisher.ts
FE/src/types/gameSubscriber.ts
FE/src/types/participant.ts

[Feat] 투표 기능 구현

---

BE/src/game/total.game-manager.ts

[Fix] 1차 투표에서 무효표가 다수표일 때 밤으로 넘어가지 않고 최종 변론으로 넘어가는 문제 해결

---

.github/workflows/deploy_FE.yml
FE/src/components/game/Bottombar.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/hooks/useOpenVidu.ts
FE/src/types/gamePublisher.ts
FE/src/types/gameSubscriber.ts

**수정 전**
수정 전에는 다음과 같이 password로 ssh 접속하였습니다.
```yml
- name: Copy files via ssh password
uses: appleboy/scp-action@v0.1.7
with:
host: ${{ secrets.HOST }}
username: ${{ secrets.USERNAME }}
password: ${{ secrets.PASSWORD }}
port: ${{ secrets.PORT }}
proxy_host: ${{ secrets.PROXY_HOST }}
proxy_username: ${{ secrets.PROXY_USERNAME }}
proxy_password: ${{ secrets.PROXY_PASSWORD }}
proxy_port: ${{ secrets.PROXY_PORT }}
source: "./FE/.next, ./FE/package.json, ./FE/package-lock.json, ./FE/public"
target: "~/mafiacamp/mafiacamp-fe"
overwrite: true
```
**수정 후**
수정 후에는 다음과 같이 private key를 사용하여 ssh 접속하도록 변경하였습니다.
```yml
- name: Copy files via ssh using key
uses: appleboy/scp-action@v0.1.7
with:
host: ${{ secrets.HOST }}
username: ${{ secrets.USERNAME }}
port: ${{ …
```

[Feat] 경찰 기능 구현

---

FE/src/components/game/GameViewer.tsx
FE/src/constants/situation.ts
FE/src/hooks/useOpenVidu.ts

다음과 같이 투표 기능이 정상적으로 동작하지 않는 오류가 발생하였습니다.
이는 닉네임을 통해 candidate 설정을 진행해야 했는데, 실수로 닉네임 대신 배열의 index를 사용해서 발생한 문제였습니다.
따라서 다음과 같이 `for-in`을 `for-of`로 수정하여 문제를 해결하였습니다.
```typescript
// 투표 시작 시 투표 대상 후보자 설정
socket?.on('send-vote-candidates', (candidates: string[]) => {
initializeVotes();
setInvalidityCount(0);
setTarget(null);
for (const nickname of candidates) {
if (nickname === gamePublisher.nickname) {
changePublisherStatus({ isCandidate: true });
} else {
changeSubscriberStatus(nickname, { isCandidate: true });
}
}
});
```
#149

[Fix] 투표 기능 오류 수정

---

FE/next.config.ts
FE/src/components/game/Bottombar.tsx
FE/src/components/game/ChattingList.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/constants/situation.ts
FE/src/hooks/useOpenVidu.ts

[Feat] 마피아 기능 구현

---

FE/next.config.ts
FE/src/app/api/login/admin/route.ts
FE/src/app/signin/admin/page.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/components/lobby/CreateRoomModal.tsx
FE/src/components/signin/AdminPanel.tsx
FE/src/components/signin/SigninPanel.tsx
FE/src/constants/toastOption.ts
FE/src/hooks/useOpenVidu.ts
FE/src/libs/zod/accountCreateFormSchema.ts

[Feat] 의사 기능 구현 & 관리자 로그인/회원가입 기능 구현

---

BE/src/common/utils/mutex-map.ts
BE/src/user/controller/user.controller.ts
BE/src/user/entity/user.entity.ts

[Fix] MutexMap 빈 생성자 제거

---

BE/test/game/usecase/allocate-user-role/random.job.factory.test.ts

[Fix] GameRoom 생성자 문제 해결

---

FE/src/components/signin/admin/AdminPanel.tsx
FE/src/hooks/useSignout.ts

[Fix] 로그인 이후 로비 페이지로 접근하지 못하는 오류 수정

---

.github/workflows/deploy_FE.yml
FE/src/components/common/Header.tsx
FE/src/components/common/HeaderSidebar.tsx
FE/src/components/home/Introduction.tsx

[Fix] 메인 페이지에서 새로고침을 통해 로그인한 사용자가 로비 페이지에 접속하지 못하는 오류 수정

---

BE/src/common/utils/lock-manager.ts
BE/src/common/utils/mutex-map.ts
BE/src/game/fsm/states/set-up.state.ts
BE/src/game/total.game-manager.ts
BE/src/game/usecase/countdown/mafia.countdown.timer.ts
BE/src/game/usecase/role-playing/mafia-manager.ts
BE/src/game/usecase/role-playing/mafia.kill.service.ts
BE/src/game/usecase/role-playing/mafia.kill.usecase.ts

```typescript
export class LockManager<K> {
private locks = new Map<K, Mutex>();
private globalMutex = new Mutex();
private getLock(key: K): Mutex {
let lock = this.locks.get(key);
if (!lock) {
lock = new Mutex();
this.locks.set(key, lock);
}
return lock;
}
async withKeyLock<T>(key: K, callback: () => Promise<T>): Promise<T> {
const lock = this.getLock(key);
const release = await lock.acquire();
try {
return await callback();
} finally {
release();
}
}
async withGlobalLock<T>(callback: () => Promise<T>): Promise<T> {
const release = await this.globalMutex.acquire();
try {
return await callback();
} finally {
release();
}
}
async releaseKey(key: K): Promise<void> {
this.locks.delete(key);
}
async clear(): Promise<void> {
return this.withGlobalLock(async () => { …
```

[Feat] LockManager 구현과 동시성 제어 변경

---

BE/src/auth/guard/user-detail.jwt.guard.ts

[Fix] Guard에서 payLoad, body 타입 변경

---

BE/src/auth/guard/common.jwt.guard.ts
BE/src/game-room/controller/game-room.controller.ts
BE/src/game-room/entity/game-room.model.ts
BE/src/game-room/game-room.module.ts
BE/src/game-room/game-room.service.ts

[Feat] Quick Start 시 빈방 Id 조회 API 구현

---

.github/workflows/deploy_FE.yml

[Fix] Front-end CI/CD 파이프라인 오류 수정

---

FE/__tests__/socketStore.test.ts
FE/src/app/api/user/nickname/route.ts
FE/src/app/layout.tsx
FE/src/components/common/header/Header.tsx
FE/src/components/common/header/HeaderSidebar.tsx
FE/src/components/common/header/NicknameModal.tsx
FE/src/components/common/header/ProfileModal.tsx
FE/src/components/game/VideoItem.tsx
FE/src/components/game/VideoViewer.tsx
FE/src/components/home/Introduction.tsx
FE/src/components/lobby/LobbyBanner.tsx
FE/src/components/lobby/LobbyViewer.tsx
FE/src/components/lobby/NicknameModal.tsx
FE/src/components/signin/admin/AdminPanel.tsx
FE/src/components/signin/loading/AuthLoading.tsx
FE/src/hooks/useChatting.ts
FE/src/hooks/useOpenVidu.ts
FE/src/hooks/useSignout.ts
FE/src/libs/zod/nicknameChangeFormSchema.ts
FE/src/stores/authStore.ts
FE/src/stores/sidebarStore.ts
FE/src/stores/socketStore.ts

[Feat] 닉네임 변경 기능 구현

---

.github/workflows/deploy_FE.yml
FE/Dockerfile
FE/next.config.ts
FE/src/app/api/rooms/vacant/route.ts
FE/src/components/common/header/Header.tsx
FE/src/components/game/Bottombar.tsx
FE/src/components/game/GameResultBoard.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/game/video/InvalidityButton.tsx
FE/src/components/game/video/VideoItem.tsx
FE/src/components/game/video/VideoViewer.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/components/lobby/LobbyList.tsx
FE/src/constants/gameStatus.ts
FE/src/constants/roomStatus.ts
FE/src/constants/situation.ts
FE/src/hooks/useOpenVidu.ts
FE/src/types/gamePublisher.ts
FE/src/types/gameSubscriber.ts
FE/src/types/room.ts

https://www.notion.so/Next-js-Docker-2c21fa3a1f4a4b898a05b3362d4ae658
Front-end 빌드 방식을 default 빌드 방식에서 standalone 방식으로 변경함으로써 Docker 이미지 크기를 상당히 줄일 수 있었습니다.
#206 
#208

[Feat] 게임 결과 표시 컴포넌트 구현 & Quick Start 기능 구현 & 방장 표시 기능 & 방장 변경 기능 & 빌드 방식 변경

---

FE/src/components/game/GameResultBoard.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/lobby/LobbyViewer.tsx
FE/src/hooks/useOpenVidu.ts

[Feat] 게임 재시작 기능 & 방장 변경 알림 기능

---

FE/src/app/api/signin/admin/route.ts
FE/src/app/api/signin/kakao/route.ts
FE/src/components/common/header/Header.tsx
FE/src/components/game/GameViewer.tsx
FE/src/components/home/Introduction.tsx
FE/src/components/lobby/ConnectedUserList.tsx
FE/src/components/lobby/LobbyList.tsx
FE/src/components/lobby/LobbyViewer.tsx
FE/src/components/signin/AuthPanel.tsx
FE/src/components/signin/loading/AuthLoading.tsx
FE/src/hooks/useChatting.ts
FE/src/hooks/useOpenVidu.ts
FE/src/stores/authStore.ts
FE/src/stores/sidebarStore.ts
FE/src/stores/socketStore.ts

https://www.notion.so/fd205dcfb33b414e959c38c833993789
#24 
#224

[Feat] 게임 방 페이지에서 새로고침을 하거나 브라우저 탭을 닫을 때 방 퇴장 기능 구현

---

FE/Dockerfile

[Fix] 프론트엔드 env 설정 오류 수정

---

FE/Dockerfile

[Fix] env 설정 오류 수정

---

BE/package-lock.json
BE/package.json
BE/src/common/filter/http.exception.filter.ts
BE/src/common/filter/websocket.exception.filter.ts
BE/src/common/logger/websocket.logger.interceptor.ts
BE/src/common/logger/winston.config.ts
BE/src/common/object/ncloud.log.transport.ts
BE/src/event/event.gateway.ts
BE/src/event/event.module.ts
BE/src/game/fsm/game-context.ts
BE/src/game/usecase/start-game/start-game.service.ts
BE/src/game/usecase/start-game/start-game.usecase.ts
BE/src/main.ts

```
client.emit('error', responseBody);
```
```
this.uploadInterval = setInterval(async () => {
await this.uploadLogs();
}, 5 * 60 * 1000);
private async uploadLogs() {
if (this.isUploading || this.logBuffer.length === 0) return;
this.isUploading = true;
const currentBuffer = [...this.logBuffer];
this.logBuffer = [];
const fileName = `${this.currentDate}.log`;
try {
let existingContent = '';
try {
const existingLog = await this.s3.getObject({
Bucket: this.bucket,
Key: fileName,
}).promise();
existingContent = existingLog.Body.toString();
} catch (error) {
console.error(error);
}
const newContent = currentBuffer.join('\n') + '\n';
const updatedContent = existingContent + newContent;
await this.s3.putObject({
Bucket: this.bucket,
Key: fileName,
Body: …
```

[Feat] log filter 구현과 log ncloud object storage 적재

---

.github/workflows/deploy_FE.yml
FE/.dockerignore
FE/Dockerfile

[Fix] deploy_FE.yml & Dockerfile 파일 수정

---

BE/src/user/user.service.ts

[Fix] 닉네임 수정 오류와 유저 탭 공유 예외 수정

---

README.md

[Docs] README에 gif 추가

---

README.md

[Docs] README.md 업데이트

---

BE/src/event/event-client-manager.ts
BE/src/event/event.gateway.ts
BE/src/event/event.module.ts
BE/src/user/user.service.ts

[Feat] 닉네임 변경 시, EventClient로 반영되도록 설정

---

BE/src/event/event-client-manager.ts
BE/src/user/user.service.ts

[Fix] UserId type 문제와 eventClient.nickname 선언 문제 해결

---

FE/src/app/layout.tsx
FE/src/components/common/header/Header.tsx
FE/src/components/lobby/LobbyBanner.tsx
FE/src/hooks/common/useNicknameManager.ts

[Feat] 닉네임 변경 시 소켓 재연결 기능

---

FE/src/components/game/Bottombar.tsx
FE/src/components/game/video/VideoFilter.tsx
FE/src/components/game/video/VideoItem.tsx
FE/src/components/game/video/VideoViewer.tsx
FE/src/constants/situation.ts
FE/src/hooks/game/useGameStatus.ts
FE/src/hooks/game/useTickingTimerAudio.ts
FE/src/hooks/game/video/useVideoItem.ts

[Feat] 1차 투표와 최종 투표 구분 & 카운트다운 시계 소리 볼륨 조정

---

FE/src/components/game/Bottombar.tsx
FE/src/components/lobby/LobbyItem.tsx
FE/src/hooks/game/useGameStatus.ts
FE/src/hooks/lobby/useLobbyList.ts
FE/src/hooks/lobby/useRoomManager.ts
FE/src/hooks/utils/useThrottle.ts

[Feat] 버튼 이벤트 중복 호출 방지 기능 구현
